server:
  address: 0.0.0.0
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:file:./test
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
